meta_product_name: "GetYoShares"
meta_title: "GetYoShares - Invest in artists' success"
meta_description: "Getyoshares allows you to bet on artists’ future success. Discover artists to support and buy a share of their earnings to come."
meta_image: "meta_picture.jpg"
